AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Accepts and transforms Facebook data
Resources: 
  team1_FBTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: lambda
        Endpoint: !GetAtt team1_FBTransform.Arn
  team1_FBIngest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fb_ingest.handler
      Runtime: python3.6
      Policies:
        Statement:
          - Effect: Allow
            Action: SNS:Publish
            Resource: !Ref team1_FBTopic
      Events:
        FBApi:
          Type: Api
          Properties:
            Path: /PushEvent
            Method: POST
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref team1_FBTopic
  team1_FBTransform:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fb_transform.handler
      Runtime: python3.6
      Events:
        FBSNS:
          Type: SNS
          Properties:
            Topic: !Ref team1_FBTopic
  team1_FBTransformInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref team1_FBTransform
      Principal: sns.amazonaws.com